POST http://localhost:8080/api/user
Content-Type: application/json

{
    "name": "testuser2",
    "surname": "testuser",
    "password": "qwerty123"
}

###

PUT http://localhost:8080/api/user
Content-Type: application/json

{
    "id": 2,
    "name": "testuser upd",
    "surname": "testuser upd",
    "password": "123"
}

###

GET http://localhost:8080/api/user

###

DELETE http://localhost:8080/api/user/3

###

GET http://localhost:8080/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InRlc3R1c2VyIiwic3VybmFtZSI6InRlc3R1c2VyIiwicGFzc3dvcmQiOiIkMmIkMDQkQzRPTnA3bTljUXRXbnNYTGVXUkJGZWxzZkM3emt3a3VQOFVVd3pyY3ZOLzBKWkxwdTJUUlciLCJpYXQiOjE2NTU0MzAyMDV9.5hRPUdKU8f-aIuCn-mOD9YAebimCuC_gsjSISobm52c

###

POST http://localhost:8080/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InRlc3R1c2VyIiwic3VybmFtZSI6InRlc3R1c2VyIiwicGFzc3dvcmQiOiIkMmIkMDQkQzRPTnA3bTljUXRXbnNYTGVXUkJGZWxzZkM3emt3a3VQOFVVd3pyY3ZOLzBKWkxwdTJUUlciLCJpYXQiOjE2NTU0MzAyMDV9.5hRPUdKU8f-aIuCn-mOD9YAebimCuC_gsjSISobm52c

{
    "title": "title post",
    "content": "content post",
    "user_id": 2
}

###

PUT http://localhost:8080/api/post
Content-Type: application/json

{
    "id": 3,
    "title": "title post",
    "content": "content post",
    "user_id": 12
}

###

POST http://localhost:8080/api/login
Content-Type: application/json

{
    "name": "testuser",
    "password": "qwerty123"
}