POST http://localhost:8080/api/user
Content-Type: application/json

{
    "name": "testuser",
    "surname": "testuser"
}

###

PUT http://localhost:8080/api/user
Content-Type: application/json

{
    "id": 12,
    "name": "testuser upd",
    "surname": "testuser upd"
}

###

GET http://localhost:8080/api/user

###
DELETE http://localhost:8080/api/user/8

###

GET http://localhost:8080/api/post

###

POST http://localhost:8080/api/post
Content-Type: application/json

{
    "title": "title post",
    "content": "content post",
    "user_id": 12
}

###

PUT http://localhost:8080/api/post
Content-Type: application/json

{
    "id": 3,
    "title": "title post",
    "content": "content post",
    "user_id": 12
}